### PR TITLE
version bump ejabberd-18.09

### PR DESCRIPTION
**Pull request by nuts424**
add ejabberd-18.09 and depended ebuilds based on [1] 

[1] https://github.com/processone/ejabberd/blob/master/rebar.config

### CODE REVIEW

**Comment by Ri0n** [comment]
Hi!
Thanks for the contribution! Just two questions.
1. does it work?
2. is 18.09 officially released?

**Comment by nuts424** [comment]
Hi!
1. It builds fine on my system. But I didn't touched the ebuild code itself or the patch files. Just noticed that http_poll isn't allowed anymore in config.
2. 18.09 released view days ago [1] 
 

[1] https://blog.process-one.net/ejabberd-18-09/

**Comment by nuts424** [comment]
Tested with:
[ebuild   R   ~] net-im/ejabberd-18.09::ejabberd-overlay  USE="nls pam zlib -captcha -debug -full-xml -hipe -ldap -mssql -mysql -odbc -postgres -redis -riak -roster-gw -sip -sqlite -stun"

**Comment by Ri0n** [comment]
thanks!

**Comment by Ri0n** [comment]
I don't see any changes in dependencies of dependencies.
Most likely compilation will file in some cases. especially on upgrade.
particularly update of p1_utils impacts many packages.

**Comment by nuts424** [comment]
Maybe its because I add new ebuilds instead changing the old ones?

**Comment by Ri0n** [comment]
ah yes second commit. it's correct, sorry :)

**Comment by Ri0n** [comment]
are you one of Gentoo devs? :)
I see you made my profiles dir nice too :)

**Comment by nuts424** [comment]
nope.. I modified profiles and metadata for my local overlay.. saw you also merged it. Is this a fault of me cause its in my PR?

**Comment by Ri0n** [comment]
it's ok. It had a lot of trash copied from another repo.

**Comment by nuts424** [comment]
Great!

Thanks for adding ejabberd to layman!

**Comment by Ri0n** [comment]
Hm but I'd brought back parts of metadata/layout.conf
particularly about ebuilds signing. It's not necessary in git.

**Comment by nuts424** [comment]
I've already thought something like that.. I threw out stuff I did not know, so feel free to readd the useful things.

**Pull request merged**
